### ISSUE TITLE
A more detailed description of running the netapps

### ISSUE THREAD

**Issue by andr01d-1** [Microchip-MPLAB-Harmony/net_apps_sam_a7g5#1]
Hello, 

Thanks for putting up a demo app. This is really helpful! I am really new to SAM series in general. I am trying to follow the [github pages](https://microchip-mplab-harmony.github.io/net_apps_sam_a7g5/GUID-1C3F069E-8D7B-4DCC-BFAF-A9BD1D9DDE2F.html) to run [TCP/IP UDP client GMAC0](https://github.com/Microchip-MPLAB-Harmony/net_apps_sam_a7g5/tree/master/apps/tcpip_udp_client/firmware/sam_a7g5_ek_GMAC0.X) demo. I am using the latest MPLAB X v6.05. I couldn't find all mismatched libraries listed in the project manifest. e.g. `v3.12.0-E1`, the net `v3.9.1` was downloaded as a dependency. But Harmony Content Manager still shows the local package unknown when importing the project.

After importing, I see the connections among modules in the graph layout. So I assume the import was successful. 

I am using the precompiled AT91 boot loader [`boot.bin`](https://github.com/Microchip-MPLAB-Harmony/net_apps_sam_a7g5/blob/master/apps/tcpip_udp_client/firmware/at91bootstrap_sam_a7g5_ek.X/build/binaries/boot.bin)

After converting the compiled GMAC0 project hex to binary and renamed the file as `harmony.bin`. I copied both files to a 64GB SDCard.

However, when I connect to the EK through uart. I still only see the default `RomBoot` text

<img width="458" alt="sc" src="https://user-images.githubusercontent.com/47770022/229442130-aaef4e20-617c-40e9-83d7-eac02743a3ce.png">

I am not sure if the SDCard boot section is running. 

Would you mind to point me to the right direction? Thank you!!

**Comment by hakim-cherif-mchp** [comment]
Hi @andr01d-1 ,

Would you accept please to open a support ticket ? 

It will be easier for our dedicated team members to track and resolve your issue. 

The link : https://microchip.my.site.com/s/newcase

Many thanks,

Best Regards,

Hakim CHERIF
Applications Engineer - Microchip MPU32 Team.

**Comment by andr01d-1** [comment]
Thanks Hakim, I have opened a ticket a few days ago. I am able to see the boot image and application binary printout through uart. Closing the issue. Thanks you and the team's help!

**Comment by hakim-cherif-mchp** [comment]
Your welcome :)
